version: '3'

services:
  web:
    image: ghcr.io/moodyzoo/tubnetplace:latest
    ports:
      - "3000:3000"
    volumes:
      - ./images:/var/tubnetplace/images
      - ./scripts:/var/tubnetplace/scripts
    depends_on:
      - postgres
    environment:
      POSTGRES_CONNECTION_URI: postgres://chief:chief@postgres/chief
      BASE_URL: https://tubnetplace.live
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: chief
      POSTGRES_USER: chief
      POSTGRES_DB: chief
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    